#ifndef __TEST_H__
#define __TEST_H__

#include "cpu/helper.h"

/* Declare functions generated by make_instr_helper */
make_helper(test_rm2r_b);
make_helper(test_rm2r_v);
make_helper(test_i2a_b);
make_helper(test_i2a_v);
make_helper(test_i2rm_b);
make_helper(test_i2rm_v);

#endif
